project:
  type: website
  output-dir: docs

website:
  title: "Sangwon Woo's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sangwon-woo
format:
  html:
    theme: cosmo
    css: styles.css



